# OS
FROM httpd 

# Maintainer
MAINTAINER Riccardo Bruno <riccardo.bruno@ct.infn.it>

# Environment for FGDB
ENV FG_USER=futuregateway\
 FG_USERPWD=futuregateway\
 FG_DIR=/home/futuregateway\
 FG_TEST=fgtest\
 FG_TESTPWD=fgtest\
 FG_TESTDIR=/home/fgtest\
 FGDB_HOST=fgdb\
 FGDB_PORT=3306\
 FGDB_USER=fgapiserver\
 FGDB_PASSWD=fgapiserver_password\
 FGDB_NAME=fgapiserver\
# Environment for scripts
 FGSETUP_GIT=https://github.com/FutureGatewayFramework/fgSetup.git\
 FGSETUP_BRANCH=master\
# Environment for GridEngine EI
 UTDB_HOST=$FGDB_HOST\
 UTDB_PORT=3306\
 UTDB_USER=tracking_user\
 UTDB_PASSWORD=usertracking\
 UTDB_DATABASE=userstracking\
# Environment for Liferay portal
 FG_PORTALEP=science_gateway
 FG_LIFERAY=http://fgliferay:8080/\


# SSL/HTTPS Certificates
ADD server.crt /usr/local/apache2/conf
ADD server.key /usr/local/apache2/conf

# Package Installation
RUN adduser --disabled-password --gecos "" $FG_USER &&\
    chown -R $FG_USER:$FG_USERS $FG_DIR &&\
    echo "$FG_USER:$FG_USERPWD" | /usr/sbin/chpasswd &&\
    adduser --disabled-password --gecos "" $FG_TEST &&\
    chown -R $FG_TEST:$FG_TEST $FG_TESTDIR &&\
    echo "$FG_TEST:$FG_TESTPWD" | /usr/sbin/chpasswd &&\
    apt-get update &&\
    apt-get install -y --no-install-recommends\
            curl\
            ca-certificates\
            sudo\
            git\
            mysql-client\
            mlocate\
            vim\
            locales &&\
   #sudo echo "$FG_USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/* &&\
    locale-gen en_US.UTF-8 &&\
    sed -i 's/#LoadModule\ ssl_module\ modules\/mod_ssl.so/LoadModule\ ssl_module\ modules\/mod_ssl.so/'\
           /usr/local/apache2/conf/httpd.conf &&\
    sed -i 's/#LoadModule\ socache_shmcb_module\ modules\/mod_socache_shmcb.so/LoadModule\ socache_shmcb_module\ modules\/mod_socache_shmcb.so/' /usr/local/apache2/conf/httpd.conf &&\
    sed -i 's/#Include\ conf\/extra\/httpd-ssl.conf/Include\ conf\/extra\/httpd-ssl.conf/'\
           /usr/local/apache2/conf/httpd.conf &&\
    sed -i 's/#LoadModule\ proxy_module\ modules\/mod_proxy.so/LoadModule\ proxy_module\ modules\/mod_proxy.so/'\
           /usr/local/apache2/conf/httpd.conf &&\
    sed -i 's/#LoadModule\ proxy_balancer_module\ modules\/mod_proxy_balancer.so/LoadModule\ proxy_balancer_module\ modules\/mod_proxy_balancer.so/'\
           /usr/local/apache2/conf/httpd.conf &&\
    sed -i 's/#LoadModule\ proxy_hcheck_module\ modules\/mod_proxy_hcheck.so/LoadModule\ proxy_hcheck_module\ modules\/mod_proxy_hcheck.so/'\
           /usr/local/apache2/conf/httpd.conf &&\
     sed -i 's/#LoadModule\ slotmem_shm_module\ modules\/mod_slotmem_shm.so/LoadModule\ slotmem_shm_module\ modules\/mod_slotmem_shm.so/'\
           /usr/local/apache2/conf/httpd.conf &&\
     sed -i 's/#LoadModule\ watchdog_module\ modules\/mod_watchdog.so/LoadModule\ watchdog_module\ modules\/mod_watchdog.so/'\
           /usr/local/apache2/conf/httpd.conf &&\
           echo "ProxyPass \"/$FG_PORTALEP\"  \"$FG_LIFERAY\"" >> /usr/local/apache2/conf/extra/proxy-html.conf &&\
           echo "ProxyPassReverse \"/$FG_PORTALEP\"  \"$FG_LIFERAY\"" >> /usr/local/apache2/conf/extra/proxy-html.conf &&\
    echo "for f in \$(find $FG_DIR/.fgprofile -type f); do source \$f; done # FGLOADENV" >> /etc/profile.d/fg_profile.sh

# User and working directory
USER $FG_USER
WORKDIR $FG_DIR

# FutureGateway scripts
RUN git clone $FGSETUP_GIT -b $FGSETUP_BRANCH &&\
    mkdir -p .fgprofile &&\
    cp fgSetup/scripts/commons .fgprofile/commons &&\
    cp fgSetup/scripts/fgdb .fgprofile/fgdb &&\
    cp fgSetup/scripts/ei_gridengine .fgprofile/ei_gridengine &&\
# Configure scripts
    sed -i "s/.*FGDB_HOST.*/export FGDB_HOST=$FGDB_HOST/" .fgprofile/fgdb &&\
    sed -i "s/.*FGDB_PORT.*/export FGDB_PORT=$FGDB_PORT/" .fgprofile/fgdb &&\
    sed -i "s/.*FGDB_USER.*/export FGDB_USER=$FGDB_USER/" .fgprofile/fgdb &&\
    sed -i "s/.*FGDB_PASSWD.*/export FGDB_PASSWD=$FGDB_PASSWD/" .fgprofile/fgdb &&\
    sed -i "s/.*FGDB_NAME.*/export FGDB_NAME=$FGDB_NAME/" .fgprofile/fgdb &&\
    sed -i "s/.*ASDB_OPTS.*/export ASDB_OPTS=''/" .fgprofile/fgdb &&\
    sed -i "s/.*FGDB_ROOTPWD.*/export FGDB_ROOTPWD=$MYSQL_ROOT_PASSWORD/" .fgprofile/fgdb 

#
# Additional setup for Executor Interfaces
#

# Grid and Cloud Engine UsersTracking database
RUN sed -i "s/.*UTDB_HOST.*/export UTDB_HOST=$UTDB_HOST/" .fgprofile/ei_gridengine &&\
    sed -i "s/.*UTDB_PORT.*/export UTDB_PORT=$UTDB_PORT/" .fgprofile/ei_gridengine &&\
#    sed -i "s/.*UTDB_USER.*/export UTDB_USER=$UTDB_USER/" .fgprofile/ei_gridengine &&\
#    sed -i "s/.*UTDB_PASSWD.*/export UTDB_PASSWD=$UTDB_PASSWD/" .fgprofile/ei_gridengine &&\
#    sed -i "s/.*UTDB_NAME.*/export UTDB_NAME=$UTDB_NAME/" .fgprofile/ei_gridengine &&\
    sed -i "s/.*UTDB_OPTS.*/export UTDB_OPTS=''/" .fgprofile/ei_gridengine

EXPOSE 80
EXPOSE 443

# Prepare and execute sshd
USER root
WORKDIR /root

